# Generated by Django 5.0.13 on 2025-12-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('capacidad_maxima', models.IntegerField()),
                ('costo_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organizador', models.CharField(max_length=100)),
                ('estado_evento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
                ('tipo_participante', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id_patrocinador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_patrocinador', models.CharField(max_length=100)),
                ('nivel_patrocinio', models.CharField(max_length=50)),
                ('contacto_persona', models.CharField(max_length=100)),
                ('email_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('sitio_web', models.CharField(max_length=255)),
                ('monto_patrocinio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda_Evento',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sesion', models.CharField(max_length=255)),
                ('descripcion_sesion', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('orador', models.CharField(max_length=100)),
                ('sala', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Evento',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_feedback', models.DateTimeField()),
                ('calificacion_general', models.IntegerField()),
                ('comentarios_adicionales', models.TextField()),
                ('sugerencias', models.TextField()),
                ('calificacion_oradores', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eventos.evento')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eventos.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Patrocinador',
            fields=[
                ('id_evento_patrocinador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_acuerdo', models.DateField()),
                ('fecha_fin_acuerdo', models.DateField()),
                ('monto_acordado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_beneficio', models.TextField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eventos.evento')),
                ('id_patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eventos.patrocinador')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField()),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_ticket', models.CharField(max_length=50)),
                ('estado_ticket', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('codigo_qr', models.CharField(max_length=255)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eventos.evento')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eventos.participante')),
            ],
        ),
    ]
