# Generated by Django 5.0.13 on 2025-12-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
