# Generated by Django 5.0.13 on 2025-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0002_alter_participante_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_evento',
            name='fecha_feedback',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='email_contacto',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
